graph LR
    ds["data source"] --- a(( )):::filled ~~~ b[ ]:::open --- model:::highlight
    classDef default fill:#00c0c3, stroke-width:0
    classDef highlight fill:#f9c437
    classDef open fill:#fff, stroke-width:2, stroke:#000
    classDef filled fill:#000, stroke-width:2, stroke:#000
