%%{
  init: { 
    'gitGraph': { 'showBranches': false},  
    'themeVariables': {  'commitLabelFontSize': '16px' }
  } 
}%%
gitGraph
    commit id: "a13fb"
    commit id: "cb28d"
    commit id: "2ef7c"
    branch develop
    commit id: "ff86a"
    checkout main
    commit id: "46cd3"
    merge develop
    commit id: "54eb9"
