%%{
  init: { 
    'gitGraph': { 'showBranches': false},  
    'themeVariables': {  'commitLabelFontSize': '16px' }
  } 
}%%
gitGraph
    commit id: "a13fb"
    commit id: "cb28d"
    commit id: "2ef7c"
